version: '3'
services:
  vulnerableWeb:
    build:
      context: ..
      dockerfile: vulnerableWeb.dockerfile
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      -
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
  vulnerableContainer:
    context: ./
    dockerfile: vulnerableCont.dockerfile