version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
      MYSQL_DATABASE: university
    volumes:
    - mysql-data:/var/lib/mysql
    - "./uni.sql:/tmp/uni.sql"

  vulndocker:
    build:
      dockerfile: vulnerableCont.dockerfile
      context: .
    restart: on-failure
    environment:
      PROFTPD_PUBLICIP: 192.168.0.84
    ports:
      - "21:21"
      - "20:20"
      - "60000-60100:60000-60100"
    network_mode: host

  proftpd:
    image: blacklabelops/proftp:1.3.5
    ports:
      - 21:21
      - 20:20


volumes:
  mysql-data:
