version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
      MYSQL_DATABASE: university
    volumes:
    - mysql-data:/var/lib/mysql

  vulndocker:
    build:
      dockerfile: vulnerableCont.dockerfile
      context: .
    restart: always
    ports:
      - 21:21
      - 20:20

volumes:
  mysql-data:
