version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./UniVulnerableWebsite/:/var/www/myapp
    depends_on:
      - php
      - mariadb

  php:
    image: php:7.2-fpm
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

volumes:
  mariadb-data: