version: "3.7"
services:
  web-server:
    image: vulncontainer_web-server
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
      MYSQL_DATABASE: university
    volumes:
      - mysql-data:/var/lib/mysql
      - "./uni.sql:/tmp/uni.sql"

  vulndocker:
    image: vulncontainer_vulndocker
    restart: on-failure
    ports:
      - 40000:21
      - 40001:2222
    volumes:
      - user-data-ftp:/home/


volumes:
  mysql-data:
  user-data-ftp:
