version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
      MYSQL_DATABASE: university
    volumes:
    - mysql-data:/var/lib/mysql
    - "./uni.sql:/tmp/uni.sql"

  vulndocker:
    build:
      dockerfile: vulnerableCont.dockerfile
      context: .
    restart: on-failure
    ports:
      - 2020:20
      - 2121:21
      - 2222:22
      - 3389:3389
    volumes:
      - user-data-ftp:/home/
    networks:
      test_net:
         ipv4_address: 172.22.0.14


volumes:
  mysql-data:
  user-data-ftp:

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
