version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
      MYSQL_DATABASE: university
    volumes:
    - mysql-data:/var/lib/mysql
    - "./uni.sql:/tmp/uni.sql"

  vulndocker:
    build:
      dockerfile: vulnerableCont.dockerfile
      context: .
    restart: on-failure
    volumes:
      - user-data-ftp:/home/
    networks:
      test_net:
         ipv4_address: 192.168.0.90


volumes:
  mysql-data:
  user-data-ftp:

networks:
  test_net:
    ipam:
      driver: overlay
      config:
        - subnet: "192.168.0.0/100"
