version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 80:80

  mariadb:
    image: arm64v8/mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
    volumes:
    - mariadb-data:/var/lib/mysql

  vulndocker:
    build:
      dockerfile: vulnerableCont.dockerfile
      context: .
    restart: always
    ports:
      - 21:21
      - 20:20

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    ports:
      - 8000:80
    depends_on:
      - mariadb
volumes:
  mariadb-data:
