version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tiaspbiqe2r
      MYSQL_DATABASE: university
    volumes:
    - mysql-data:/var/lib/mysql
    - "./uni.sql:/tmp/uni.sql"

  vulndocker:
    build:
      dockerfile: vulnerableCont.dockerfile
      context: .
    restart: on-failure
    networks:
      default:
        external:
          name: vulnnetwork
    ports:
      - 20:20
      - 21:21
      - 22:22
      - 3389:3389
    volumes:
      - user-data-ftp:/home/

volumes:
  mysql-data:
  user-data-ftp:
