version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./UniVulnerableWebsite/:/var/www/html/"
    ports:
      - 8080:80
    links:
      - mariadb

  mariadb:
    build:
      dockerfile: mariadb.dockerfile
      context: .
    volumes:
    - mariadb-data:/var/lib/mysql

  vulndocker:
    build:
      dockerfile: vulnerableCont.dockerfile
      context: .
    restart: always
    ports:
      - 21:21
      - 20:20

volumes:
  mariadb-data:
